webtalk_init -webtalk_dir C:/FPGA/AP_5v_1clk/AP_5v.sim/sim_1/synth/func/xsim/xsim.dir/sim_tb_top_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 23 11:47:15 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211845165_1777536263_210686808_466" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "533eb3a3-d61f-494e-84d2-2272591f93f6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "075c6cb9fca44755931b91b0ee412172" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "42.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "127379552651 fs" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "302.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "204256_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4277335458 -regid "211845165_1777536263_210686808_466" -xml C:/FPGA/AP_5v_1clk/AP_5v.sim/sim_1/synth/func/xsim/xsim.dir/sim_tb_top_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/FPGA/AP_5v_1clk/AP_5v.sim/sim_1/synth/func/xsim/xsim.dir/sim_tb_top_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/FPGA/AP_5v_1clk/AP_5v.sim/sim_1/synth/func/xsim/xsim.dir/sim_tb_top_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
